import { loadGithubRepo } from "./github-loader";

import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI1 = new GoogleGenerativeAI(process.env.GEMINI_API_KEY_1!);
const model1 = genAI1.getGenerativeModel({ model: "gemini-2.0-flash-lite" });

const genAI2 = new GoogleGenerativeAI(process.env.GEMINI_API_KEY_2!);
const model2 = genAI2.getGenerativeModel({ model: "gemini-2.0-flash-lite" });

const genAI3 = new GoogleGenerativeAI(process.env.GEMINI_API_KEY_3!);
const model3 = genAI3.getGenerativeModel({ model: "gemini-2.0-flash-lite" });

const genAI4 = new GoogleGenerativeAI(process.env.GEMINI_API_KEY_4!);
const model4 = genAI4.getGenerativeModel({ model: "gemini-2.0-flash-lite" });


let _embeddingCounter = 0;
const _gens = [genAI1, genAI2, genAI3, genAI4];

export const getEmbeddings = async (text: string) => {
    // Round-robin selection across the 4 genAI instances
    const idx = (_embeddingCounter++) % _gens.length;
    const selectedGen = _gens[idx];
    if (!selectedGen) {
        throw new Error(`No generative AI instance available for index ${idx}`);
    }

    // For embeddings, use the Text Embeddings model
    const model = selectedGen.getGenerativeModel({ model: "text-embedding-004" });

    const result = await model.embedContent(text);
    const embedding = result.embedding;
    console.log(`embedding generated by genAI${idx + 1}, length:`, embedding.values.length);
    return embedding.values as number[];
}



export const getSummary = async (doc: Awaited<ReturnType<typeof loadGithubRepo>>[number]) => {
    console.log("getting summary for", doc.metadata.source);
    const code = doc.pageContent.slice(0, 10000); // Limit to 10000 characters
    const response = await model1.generateContent([
        `You are an intelligent senior software engineer who specialises in onboarding junior software engineers onto projects`,
        `You are onboarding a junior software engineer and explaining to them the purpose of the ${doc.metadata.source} file
Here is the code:
---
${code}
---
            Give a summary no more than 100 words of the code above`,
    ]);

    console.log("code summarized succesfully using gemini: ", response.response.text());
    return response.response.text()
}





export const aiSummariseCommit = async (diff: string) => {
    const response = await model2.generateContent([
        `You are an expert programmer, and you are trying to summarize a git diff.
Reminders about the git diff format:
For every file, there are a few metadata lines, like (for example):
\`\`\`
diff --git a/lib/index.js b/lib/index.js
index aadf691..bfef603 100644
--- a/lib/index.js
+++ b/lib/index.js
\`\`\`
This means that \`lib/index.js\` was modified in this commit. Note that this is only an example.
Then there is a specifier of the lines that were modified.
A line starting with \`+\` means it was added.
A line that starting with \`-\` means that line was deleted.
A line that starts with neither \`+\` nor \`-\` is code given for context and better understanding.
It is not part of the diff.
[...]
EXAMPLE SUMMARY COMMENTS:
\`\`\`
* Raised the amount of returned recordings from \`10\` to \`100\` [packages/server/recordings_api.ts], [packages/server/constants.ts]
* Fixed a typo in the github action name [.github/workflows/gpt-commit-summarizer.yml]
* Moved the \`octokit\` initialization to a separate file [src/octokit.ts], [src/index.ts]
* Added an OpenAI API for completions [packages/utils/apis/openai.ts]
* Lowered numeric tolerance for test files
\`\`\`
Most commits will have less comments than this examples list.
The last comment does not include the file names,
because there were more than two relevant files in the hypothetical commit.
Do not include parts of the example in your summary.
It is given only as an example of appropriate comments.`,
        `Please summarise the following diff file: \n\n${diff}`,
    ]);

    return response.response.text();
};


// const result = await getEmbeddings("The quick brown fox jumps over the lazy dog.");
// console.log(result.length);
// const summary = await getSummary({
//     metadata: { source: "test.ts" }, pageContent: `
//     import { useState } from "react";
//     const [count, setCount] = useState(0);
//     function handleClick() {
//         setCount(count + 1);
//     }
//     ` });
// console.log(summary);
